version = 1

# Analizador principal de Java: estilo, bugs, code smells
[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "21"

# Cobertura de pruebas (lee jacoco.xml que mandas en GitHub Actions)
[[analyzers]]
name = "test-coverage"
enabled = true

# Detección de secretos (tokens, claves, passwords hardcodeadas)
[[analyzers]]
name = "secrets"
enabled = true

# Buenas prácticas en dependencias y configuración
[[analyzers]]
name = "docker"
enabled = true

# Ignorar archivos generados o irrelevantes
exclude_patterns = [
  "target/**",
  "**/node_modules/**",
  "**/build/**",
  "**/.mvn/**",
  "**/test/**",
  ".github/**"
]
