version = 1

# Analizador principal de Java: estilo, bugs, code smells
[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "21"

# Cobertura de pruebas (lee jacoco.xml que mandas en GitHub Actions)
[[analyzers]]
name = "test-coverage"
enabled = true

# Detecci칩n de secretos (tokens, claves, passwords hardcodeadas)
[[analyzers]]
name = "secrets"
enabled = true

# Seguridad en el c칩digo (vulnerabilidades, SQL injection, XSS, etc.)
[[analyzers]]
name = "security"
enabled = true

# Buenas pr치cticas en dependencias y configuraci칩n
[[analyzers]]
name = "docker"
enabled = true

# Patrones comunes en configuraciones YAML (si usas workflows o configs en el repo)
[[analyzers]]
name = "yaml"
enabled = true

# Ignorar archivos generados o irrelevantes
exclude_patterns = [
  "target/**",
  "**/node_modules/**",
  "**/build/**",
  "**/.mvn/**",
  "**/test/**",
  ".github/**"
]
