# .github/workflows/codacy.yml
name: Codacy Coverage
on:
  push:
    branches: [ main, develop ]

jobs:
  codacy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
      - name: Run tests with coverage
        run: mvn clean test jacoco:report
      - name: Send to Codacy
        run: |
          docker run -v $(pwd):/src \
          -e CODACY_PROJECT_TOKEN=${{ secrets.CODACY_PROJECT_TOKEN }} \
          codacy/codacy-coverage-reporter report \
          -l Java -r /src/target/site/jacoco/jacoco.xml
